name: labeler

on: [ pull_request ]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '10'
          s_max_size: '40'
          m_max_size: '85'
          l_max_size: '150'
          fail_if_xl: 'true'
          message_if_xl: 'This PR is sooooo big!! 😳'